aurae_VERSION = "1.0"
aurae_FULLVERSION = "aurae v"..aurae_VERSION

-- EN

aurae_DESCRIPTION = "Allow to monitor Crowd Control effects, for any class."

aurae_PROFILE_TEXT = "Profile: "

aurae_EFFECT = "Effect"
aurae_NAME = "Name"
aurae_DURATION = "Duration"
aurae_RESET = "New"
aurae_ADD = "Add"
aurae_MODIFY = "Modify"
aurae_EDIT = "Edit"
aurae_DELETE = "Delete"
aurae_LEARN_DELETE_PROMPT = "Are you sure you want to delete the effect "
aurae_REMOVED_NOTICE = "Removed skill effect : "
aurae_TYPE = "Type"
aurae_GROUP = "Group"
aurae_DR = "DR"
aurae_MONITOR = "Monitor"
aurae_WARN = "Warn"
aurae_ADDEDMODIFIED = " added/modified."

aurae_OPTIONS_BARS_TAB = "Bars"
aurae_OPTIONS_EFFECTS_TAB = "Monitoring"
aurae_OPTIONS_LEARN_TAB = "Skills"

aurae_OPTIONS_TRANS = "Transparency"
aurae_OPTIONS_SCALE = "Scaling"
aurae_OPTIONS_DONE = "Done"
aurae_OPTIONS_UNLOCK = "Unlock"
aurae_OPTIONS_WIDTH = "Width"
aurae_OPTIONS_INVERT = "Invert"
aurae_OPTIONS_LEADINGTIMER = "Leading Timer"
aurae_OPTIONS_ARCANIST = "Arcanist' Set"

aurae_OPTIONS_WARN_APPLIED = "Applied"
aurae_OPTIONS_WARN_FADED = "Faded"
aurae_OPTIONS_WARN_BROKEN = "Broken"
aurae_OPTIONS_WARN_LOWTIME = "Low Time"

aurae_OPTIONS_MAGE = "Mage"
aurae_OPTIONS_PRIEST = "Priest"
aurae_OPTIONS_DRUID = "Druid"
aurae_OPTIONS_HUNTER = "Hunter"
aurae_OPTIONS_PALADIN = "Paladin"
aurae_OPTIONS_WARLOCK = "Warlock"
aurae_OPTIONS_WARRIOR = "Warrior"
aurae_OPTIONS_ROGUE = "Rogue"
aurae_OPTIONS_SHAMAN = "Shaman"
aurae_OPTIONS_MISC = "Other"

aurae_OPTION_STYLE_CURRENT = "Current target"
aurae_OPTION_STYLE_RECENT = "Recent targets"
aurae_OPTION_STYLE_ALL = "Any Creature/Enemy"

aurae_OPTION_GROWTH_UP = "Growth Up"
aurae_OPTION_GROWTH_DOWN = "Growth Down"

aurae_OPTION_DR_NEVER = "Never"
aurae_OPTION_DR_MOBPLAYERS = "Mob+Players"
aurae_OPTION_DR_PLAYERS = "Players"

aurae_OPTIONS_MONITOR_CC = "Monitor CC"
aurae_OPTIONS_MONITOR_DEBUFF = "Monitor Debuffs"
aurae_OPTIONS_MONITOR_BUFF = "Monitor Buffs"

aurae_OPTIONS_COLOROVERTIME = "Use coloration over time"
aurae_OPTIONS_USECOLOR = "Specify color"

aurae_WARN_EMOTE = "announces that ";
aurae_WARN_LOWTIME = "[%s] will no more be afflicted by [%s] in %d seconds."
aurae_WARN_APPLIED = "[%s] is now afflicted by [%s]."
aurae_WARN_FADED = "[%s] is no more afflicted by [%s] (faded)."
aurae_WARN_BROKEN = "[%s] is no more afflicted by [%s] (broken)."

-- Priest
aurae_SHACKLE = "Shackle Undead"
aurae_PSYCHICSCREAM = "Psychic Scream"
aurae_BLACKOUT = "Blackout"
aurae_SHADOWWORDPAIN = "Shadow Word: Pain"
aurae_POWERWORDSHIELD = "Shadow Word: Shield"
aurae_DEVOURINGPLAGUE = "Devouring Plague"
aurae_WEAKENEDSOUL = "Weakened Soul"
aurae_RENEW ="Renew"
aurae_HOLYFIRE = "Holy Fire"
aurae_POWERINFUSION = "Power Infusion"

-- Mage
aurae_POLYMORPH = "Polymorph"
aurae_FROSTNOVA = "Frost Nova"
aurae_FROSTBITE = "Frostbite"
aurae_ICEBLOCK = "Ice Block"
aurae_FROSTBOLT = "Frostbolt"
aurae_CONEOFCOLD = "Cone of Cold"
aurae_COUNTERSPELL = "Counterspell - Silenced"
aurae_FIREBALL = "Fireball"
aurae_PYROBLAST = "Pyroblast"
aurae_IGNITE = "Ignite"
aurae_FLAMESTRIKE = "Flamestrike"
aurae_BLASTWAVE = "Blast Wave"
aurae_FROSTARMOR = "Chilled"
aurae_DETECTMAGIC = "Detect Magic"
aurae_EVOCATION = "Evocation"
aurae_ARCANEPOWER = "Arcane Power"

-- Paladin
aurae_HOJ = "Hammer of Justice"
aurae_TURNUNDEAD = "Turn Undead"
aurae_REPENTANCE = "Repentance"
aurae_DIVINESHIELD = "Divine Shield"
aurae_BOPROTECTION = "Blessing of Protection"
aurae_BOFREEDOM = "Blessing of Freedom"

-- Warlock
aurae_FEAR = "Fear"
aurae_BANISH = "Banish"
aurae_SEDUCE = "Seduction"
aurae_HOWLOFTERROR = "Howl of Terror"
aurae_DEATHCOIL = "Death Coil"
aurae_IMMOLATE = "Immolate"
aurae_CORRUPTION = "Corruption"
aurae_CURSEOFRECKLESSNESS = "Curse of Recklessness"
aurae_CURSEOFAGONY = "Curse of Agony"
aurae_CURSEOFWEAKNESS = "Curse of Weakness"
aurae_CURSEOFTONGUES = "Curse of Tongues"
aurae_CURSEOFSHADOW = "Curse of Shadow"
aurae_CURSEOFELEMENTS = "Curse of the Elements"
aurae_CURSEOFEXHAUSTION = "Curse of Exhaustion"
aurae_CURSEOFDOOM = "Curse of Doom"
aurae_SIPHONLIFE = "Siphon Life"
aurae_IMPROVEDSHADOWBOLT = "Improved Shadow Bolt"
aurae_SACRIFICE = "Sacrifice"
aurae_SPELLSTONE = "Spellstone"
aurae_SPELLLOCK = "Spell Lock"


-- Druid
aurae_HIBERNATE = "Hibernate"
aurae_ROOTS = "Entangling Roots"
aurae_POUNCE = "Pounce"
aurae_BASH = "Bash"
aurae_FERALCHARGE = "Feral Charge"
aurae_IMPSTARFIRE = "Improved Starfire"
aurae_MOONFIRE = "Moonfire"
aurae_INSECTSWARM = "Insect Swarm"
aurae_NATURESGRASP = "Nature's Grasp"
aurae_REJUVENATION = "Rejuvenation"
aurae_DASH = "Dash"
aurae_FAERIEFIRE = "Faerie Fire"
aurae_FAERIEFIREFERAL = "Faerie Fire (Feral)"
aurae_INSECTSWARM = "Insect Swarm"
aurae_INNERVATE = "Innervate"
aurae_BARKSKIN = "Barkskin"
aurae_REGROWTH = "Regrowth"
aurae_FREGEN = "Frenzied Regeneration"


-- Hunter
aurae_FREEZINGTRAP = "Freezing Trap Effect"
aurae_FREEZINGTRAP_SPELL = "Freezing Trap"
aurae_SCAREBEAST = "Scare Beast"
aurae_IMPCS = "Improved Concussive Shot"
aurae_SCATTERSHOT = "Scatter Shot"
aurae_INTIMIDATION = "Intimidation"
aurae_COUNTERATTACK = "Counterattack"
aurae_WYVERNSTING = "Wyvernsting"
aurae_IMPROVEDWINGCLIP = "Improved Wingclip"
aurae_ENTRAPMENT = "Entrapment"
aurae_SERPENTSTING = "Serpent Sting"
aurae_VIPERSTING = "Viper Sting"
aurae_DETERRENCE = "Deterrence"
aurae_RAPIDFIRE = "Rapid Fire"

-- Warrior
aurae_INTERCEPT = "Intercept Stun"
aurae_MACESPE = "Mace Specialization"
aurae_HAMSTRING = "Hamstring"
aurae_IMPHAMSTRING = "Improved Hamstring"
aurae_INTIMIDATINGSHOUT = "Intimidating Shout"
aurae_IMPREVENGE = "Revenge Stun"
aurae_CONCUSSIONBLOW = "Concussion Blow"
aurae_BERSERKERRAGE = "Berserker Rage"
aurae_BLOODRAGE = "Bloodrage"
aurae_REND = "Rend"
aurae_DISARM = "Disarm"
aurae_LASTSTAND = "Last Stand"
aurae_RETALIATION = "Retaliation"
aurae_SHIELDWALL = "Shield Wall"
aurae_DEATHWISH = "Death Wish"
aurae_IMPSHIELDBASH = "Shield Bash - Silenced"
aurae_MORTALSTRIKE = "Mortal Strike"
aurae_RECKLESSNESS = "Recklessness"
aurae_HAMSTRING = "Hamstring"

--Rogue
aurae_GOUGE = "Gouge"
aurae_BLIND = "Blind"
aurae_KS = "Kidney Shot"
aurae_CS = "Cheap Shot"
aurae_SAP = "Sap"
aurae_RUPTURE = "Rupture"
aurae_GAROTTE = "Garrote"
aurae_RIPOSTE = "Riposte"
aurae_IMPROVEDKICK = "Kick - Silenced"
aurae_ADRENALINERUSH = "Adrenaline Rush"
aurae_EVASION = "Evasion"
aurae_ROGUESPRINT = "Sprint"
aurae_BLADEFLURRY = "Blade Flurry"
aurae_CRIPPLINGP = "Crippling Poison"
aurae_DEADLYP = "Deadly Poison"

-- Shaman
aurae_FROSTSHOCK = "Frost Shock"
aurae_FLAMESHOCK = "Flame Shock"
aurae_FROSTBRANDWEAPON = "Frostbrand Weapon"
aurae_STORMSTRIKE = "Stormstrike"

-- Miscellaneous
aurae_WARSTOMP = "War Stomp"
aurae_SLEEP = "Sleep"
aurae_NETOMATIC = "Net-o-Matic"
aurae_ROCKETHELM = "Reckless Charge"

aurae_WOTF = "Will of the Forsaken"
aurae_PERCEPTION = "Perception"

aurae_RANK = "rank"
aurae_DETECTED = "detected"
aurae_NOTDETECTED = "not detected"

aurae_ENABLED = "aurae enabled"
aurae_DISABLED = "aurae disabled"

aurae_LOCKED = "aurae locked"
aurae_UNLOCKED = "aurae unlocked"

aurae_INVERSION_ON = "aurae inversion on"
aurae_INVERSION_OFF = "aurae inversion off"

aurae_STYLE_CURRENT = "Monitoring current target only"
aurae_STYLE_RECENT = "Monitoring recent targets"
aurae_STYLE_ALL = "Monitoring ALL TARGETS"

aurae_GROW_OFF = "aurae bar growth off"
aurae_GROW_UP = "aurae bar growth up"
aurae_GROW_DOWN = "aurae bar growth down"

aurae_TIMERS_OFF = "Timers off"
aurae_TIMERS_ON = "Timers on"
aurae_TIMERS_REVERSE = "Reversed Timers"

aurae_ARCANIST_ON = "Arcanist' Set activated (+15 sec to "..aurae_POLYMORPH.." spell)"
aurae_ARCANIST_OFF = "Arcanist' Set off"

aurae_COLOROVERTIME_ON = "Bar coloration over time enabled"
aurae_COLOROVERTIME_OFF = "Bar coloration over time disabled"
aurae_LEADINGTIMER_ON = "Timer position: leading"
aurae_LEADINGTIMER_OFF = "Timer position: trailing"
aurae_WARNCC_SETTO = "Warning output set to: "
aurae_WARNCC_CUSTOM = "Custom cc used (standard cc are EMOTE, SAY, PARTY, RAID, YELL): "
aurae_WARN_DISABLED = "Chat alerts disabled"
aurae_WARN_ENABLED = "Chat alerts enabled"

aurae_SCALE = "aurae Scale set to "

aurae_WIDTH = "aurae Width set to "

aurae_ALPHA = "aurae Alpha set to "

aurae_LOADED = " Loaded - /aurae"

aurae_HELP1  = " : Usage - /aurae option"
aurae_HELP2  = "options:"
aurae_HELP3  = " on     : Enables aurae"
aurae_HELP4  = " off    : Disables aurae"
aurae_HELP5  = " lock   : Locks aurae and enables"
aurae_HELP6  = " unlock : Allows you to move aurae"
aurae_HELP7  = " u      : Update improved skill ranks"
aurae_HELP8  = " print  : Prints the current configuration"
aurae_HELP9  = " invert : Invert progress bar direction"
aurae_HELP10 = " scale  : Scale aurae, use 0.25 to 3.0"
aurae_HELP11 = " width  : Set bar width, use 50 to 300"
aurae_HELP12 = " alpha  : Set bar alpha, use 0 to 1"
aurae_HELP13 = " grow   : Set bar growth up, down or off"
aurae_HELP14 = " config : Show the configuration frame"
aurae_HELP15 = " timers : Set timers display off, on or rev (countdown)"
