local _G = getfenv(0)

_G.aurae_EFFECT = "Effect"
_G.aurae_NAME = "Name"
_G.aurae_DURATION = "Duration"
_G.aurae_RESET = "New"
_G.aurae_ADD = "Add"
_G.aurae_MODIFY = "Modify"
_G.aurae_EDIT = "Edit"
_G.aurae_DELETE = "Delete"
_G.aurae_LEARN_DELETE_PROMPT = "Are you sure you want to delete the effect "
_G.aurae_REMOVED_NOTICE = "Removed skill effect : "
_G.aurae_TYPE = "Type"
_G.aurae_GROUP = "Group"
_G.aurae_DR = "DR"
_G.aurae_MONITOR = "Monitor"
_G.aurae_ADDEDMODIFIED = " added/modified."

_G.aurae_OPTIONS_BARS_TAB = "Bars"
_G.aurae_OPTIONS_EFFECTS_TAB = "Monitoring"
_G.aurae_OPTIONS_LEARN_TAB = "Skills"

_G.aurae_OPTIONS_DONE = "Done"
_G.aurae_OPTIONS_UNLOCK = "Unlock"
_G.aurae_OPTIONS_WIDTH = "Width"
_G.aurae_OPTIONS_INVERT = "Invert"
_G.aurae_OPTIONS_LEADINGTIMER = "Leading Timer"
_G.aurae_OPTIONS_ARCANIST = "Arcanist' Set"

_G.aurae_OPTIONS_MAGE = "Mage"
_G.aurae_OPTIONS_PRIEST = "Priest"
_G.aurae_OPTIONS_DRUID = "Druid"
_G.aurae_OPTIONS_HUNTER = "Hunter"
_G.aurae_OPTIONS_PALADIN = "Paladin"
_G.aurae_OPTIONS_WARLOCK = "Warlock"
_G.aurae_OPTIONS_WARRIOR = "Warrior"
_G.aurae_OPTIONS_ROGUE = "Rogue"
_G.aurae_OPTIONS_SHAMAN = "Shaman"
_G.aurae_OPTIONS_MISC = "Other"

_G.aurae_OPTION_STYLE_CURRENT = "Current target"
_G.aurae_OPTION_STYLE_RECENT = "Recent targets"
_G.aurae_OPTION_STYLE_ALL = "Any Creature/Enemy"

_G.aurae_OPTION_GROWTH_UP = "Growth Up"
_G.aurae_OPTION_GROWTH_DOWN = "Growth Down"

_G.aurae_OPTION_DR_NEVER = "Never"
_G.aurae_OPTION_DR_MOBPLAYERS = "Mob+Players"
_G.aurae_OPTION_DR_PLAYERS = "Players"

_G.aurae_OPTIONS_MONITOR_CC = "Monitor CC"
_G.aurae_OPTIONS_MONITOR_DEBUFF = "Monitor Debuffs"
_G.aurae_OPTIONS_MONITOR_BUFF = "Monitor Buffs"

_G.aurae_OPTIONS_COLOROVERTIME = "Use coloration over time"
_G.aurae_OPTIONS_USECOLOR = "Specify color"

-- Druid
_G.aurae_HIBERNATE = "Hibernate"
_G.aurae_ROOTS = "Entangling Roots"
_G.aurae_POUNCE = "Pounce"
_G.aurae_BASH = "Bash"
_G.aurae_FERALCHARGE = "Feral Charge"
_G.aurae_IMPSTARFIRE = "Improved Starfire"
_G.aurae_MOONFIRE = "Moonfire"
_G.aurae_INSECTSWARM = "Insect Swarm"
_G.aurae_NATURESGRASP = "Nature's Grasp"
_G.aurae_REJUVENATION = "Rejuvenation"
_G.aurae_DASH = "Dash"
_G.aurae_FAERIEFIRE = "Faerie Fire"
_G.aurae_FAERIEFIREFERAL = "Faerie Fire (Feral)"
_G.aurae_INSECTSWARM = "Insect Swarm"
_G.aurae_INNERVATE = "Innervate"
_G.aurae_BARKSKIN = "Barkskin"
_G.aurae_REGROWTH = "Regrowth"
_G.aurae_FREGEN = "Frenzied Regeneration"

-- Warrior
_G.aurae_INTERCEPT = "Intercept Stun"
_G.aurae_MACESPE = "Mace Specialization"
_G.aurae_HAMSTRING = "Hamstring"
_G.aurae_IMPHAMSTRING = "Improved Hamstring"
_G.aurae_INTIMIDATINGSHOUT = "Intimidating Shout"
_G.aurae_IMPREVENGE = "Revenge Stun"
_G.aurae_CONCUSSIONBLOW = "Concussion Blow"
_G.aurae_BERSERKERRAGE = "Berserker Rage"
_G.aurae_BLOODRAGE = "Bloodrage"
_G.aurae_REND = "Rend"
_G.aurae_DISARM = "Disarm"
_G.aurae_LASTSTAND = "Last Stand"
_G.aurae_RETALIATION = "Retaliation"
_G.aurae_SHIELDWALL = "Shield Wall"
_G.aurae_DEATHWISH = "Death Wish"
_G.aurae_IMPSHIELDBASH = "Shield Bash - Silenced"
_G.aurae_MORTALSTRIKE = "Mortal Strike"
_G.aurae_RECKLESSNESS = "Recklessness"
_G.aurae_HAMSTRING = "Hamstring"

--Rogue
_G.aurae_GOUGE = "Gouge"
_G.aurae_BLIND = "Blind"
_G.aurae_KS = "Kidney Shot"
_G.aurae_CS = "Cheap Shot"
_G.aurae_SAP = "Sap"
_G.aurae_RUPTURE = "Rupture"
_G.aurae_GAROTTE = "Garrote"
_G.aurae_RIPOSTE = "Riposte"
_G.aurae_IMPROVEDKICK = "Kick - Silenced"
_G.aurae_ADRENALINERUSH = "Adrenaline Rush"
_G.aurae_EVASION = "Evasion"
_G.aurae_ROGUESPRINT = "Sprint"
_G.aurae_BLADEFLURRY = "Blade Flurry"
_G.aurae_CRIPPLINGP = "Crippling Poison"
_G.aurae_DEADLYP = "Deadly Poison"

-- Miscellaneous
_G.aurae_WARSTOMP = "War Stomp"
_G.aurae_SLEEP = "Sleep"
_G.aurae_NETOMATIC = "Net-o-Matic"
_G.aurae_ROCKETHELM = "Reckless Charge"

_G.aurae_WOTF = "Will of the Forsaken"
_G.aurae_PERCEPTION = "Perception"

_G.aurae_RANK = "rank"
_G.aurae_DETECTED = "detected"
_G.aurae_NOTDETECTED = "not detected"

_G.aurae_ENABLED = "aurae enabled"
_G.aurae_DISABLED = "aurae disabled"

_G.aurae_INVERSION_ON = "aurae inversion on"
_G.aurae_INVERSION_OFF = "aurae inversion off"

_G.aurae_STYLE_CURRENT = "Monitoring current target only"
_G.aurae_STYLE_RECENT = "Monitoring recent targets"
_G.aurae_STYLE_ALL = "Monitoring ALL TARGETS"

_G.aurae_GROW_OFF = "aurae bar growth off"
_G.aurae_GROW_UP = "aurae bar growth up"
_G.aurae_GROW_DOWN = "aurae bar growth down"

_G.aurae_TIMERS_OFF = "Timers off"
_G.aurae_TIMERS_ON = "Timers on"
_G.aurae_TIMERS_REVERSE = "Reversed Timers"

_G.aurae_ARCANIST_ON = "Arcanist' Set activated (+15 sec to ".."Polymorph".." spell)"
_G.aurae_ARCANIST_OFF = "Arcanist' Set off"

_G.aurae_COLOROVERTIME_ON = "Bar coloration over time enabled"
_G.aurae_COLOROVERTIME_OFF = "Bar coloration over time disabled"
_G.aurae_LEADINGTIMER_ON = "Timer position: leading"
_G.aurae_LEADINGTIMER_OFF = "Timer position: trailing"
