function CCWatch_ConfigDebuff()

-- required attributes: GROUP, DURATION, DIMINISHES
--  ETYPE = Effect Type : ETYPE_CC Pure CC(Stun/Root), ETYPE_DEBUFF Debuff(Snare/DoT,...), ETYPE_BUFF Buff
--  GROUP = Bar this CC is placed on
--  DURATION = Duration of CC
--  DIMINISHES = 0 never diminishes, 1 = always diminishes, 2 = diminishes on players only
-- optional attributes PVPCC, COMBO
--  PVPCC = if PVPCC exists this value will be used as the base max for a Player target
--  COMBO = if COMBO exists then Combo Points will be added to CC duration
--
-- TARGET, PLAYER, TIMER_START, TIMER_END, DIMINISH are required for all and should be initialized empty
-- MONITOR is required for all and should be initialized to true
-- WARN is required for all and should be initialized to 0

-- Rogue - Debuffs
CCWATCH.CCS[CCWATCH_RUPTURE] = {
	ICON = 'Ability_Rogue_Rupture',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 2,
	COMBO = true,
	A = 4, -- f(x) = A * x + DURATION
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_GAROTTE] = {
	ICON = 'Ability_Rogue_Garrote',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 18,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_RIPOSTE] = {
	ICON = 'Ability_Warrior_Challange',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 6,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CRIPPLINGP] = {
	ICON = 'Ability_PoisonSting',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 12,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_DEADLYP] = {
	ICON = 'Ability_Rogue_DualWeild',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 12,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_IMPROVEDKICK] = {
	ICON = 'Ability_Kick',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 2,
	MONITOR = true,
	WARN = 0,
}

-- Priest - Debuffs
CCWATCH.CCS[CCWATCH_SHADOWWORDPAIN] = {
	ICON = 'Spell_Shadow_ShadowWordPain',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 18,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_DEVOURINGPLAGUE] = {
	ICON = 'Spell_Shadow_BlackPlague',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 24,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_WEAKENEDSOUL] = {
	ICON = 'Spell_Holy_AshesToAshes',
	SCHOOL = CCWATCH_SCHOOL.HOLY,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 15,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_HOLYFIRE] = {
	ICON = 'Spell_Holy_SearingLight',
	SCHOOL = CCWATCH_SCHOOL.HOLY,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 10,
	MONITOR = true,
	WARN = 0,
}

-- Mage - Debuffs
CCWATCH.CCS[CCWATCH_DETECTMAGIC] = {
	ICON = 'Spell_Holy_Dizzy',
	SCHOOL = CCWATCH_SCHOOL.ARCANE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 120,
	MONITOR = false,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_FROSTBOLT] = {
	ICON = 'Spell_Frost_FrostBolt02',
	SCHOOL = CCWATCH_SCHOOL.FROST,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 5,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CONEOFCOLD] = {
	ICON = 'Spell_Frost_Glacier',
	SCHOOL = CCWATCH_SCHOOL.FROST,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 8,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_COUNTERSPELL] = {
	ICON = 'Spell_Frost_IceShock',
	SCHOOL = CCWATCH_SCHOOL.ARCANE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 4,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_FIREBALL] = {
	ICON = 'Spell_Fire_FlameBolt',
	SCHOOL = CCWATCH_SCHOOL.FIRE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 4,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_PYROBLAST] = {
	ICON = 'Spell_Fire_Fireball02',
	SCHOOL = CCWATCH_SCHOOL.FIRE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 12,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_IGNITE] = {
	ICON = 'Spell_Fire_Incinerate',
	SCHOOL = CCWATCH_SCHOOL.FIRE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 4,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_FLAMESTRIKE] = {
	ICON = 'Spell_Fire_SelfDestruct',
	SCHOOL = CCWATCH_SCHOOL.FIRE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 8,
	MONITOR = false,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_BLASTWAVE] = {
	ICON = 'Spell_Holy_Excorcism_02',
	SCHOOL = CCWATCH_SCHOOL.FIRE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 6,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_FROSTARMOR] = {
	ICON = 'Spell_Frost_FrostArmor02',
	SCHOOL = CCWATCH_SCHOOL.FROST,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 8,
	MONITOR = true,
	WARN = 0,
}

-- Druid - Debuffs
CCWATCH.CCS[CCWATCH_FAERIEFIRE] = {
	ICON = 'Spell_Nature_FaerieFire',
	SCHOOL = CCWATCH_SCHOOL.NATURE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 40,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_FAERIEFIREFERAL] = {
	ICON = 'Spell_Nature_FaerieFire',
	SCHOOL = CCWATCH_SCHOOL.NATURE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 40,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_MOONFIRE] = {
	ICON = 'Spell_Nature_StarFall',
	SCHOOL = CCWATCH_SCHOOL.ARCANE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 8,
	MONITOR = true,
	WARN = 0,
}

-- Hunter - Debuffs
CCWATCH.CCS[CCWATCH_SERPENTSTING] = {
	ICON = 'Ability_Hunter_Quickshot',
	SCHOOL = CCWATCH_SCHOOL.NATURE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 15,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_VIPERSTING] = {
	ICON = 'Ability_Hunter_AimedShot',
	SCHOOL = CCWATCH_SCHOOL.NATURE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 8,
	MONITOR = true,
	WARN = 0,
}

-- Paladin - Debuffs

-- Warlock - Debuffs
CCWATCH.CCS[CCWATCH_IMMOLATE] = {
	ICON = 'Spell_Fire_Immolation',
	SCHOOL = CCWATCH_SCHOOL.FIRE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 15,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CORRUPTION] = {
	ICON = 'Spell_Shadow_AbominationExplosion',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 18,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CURSEOFAGONY] = {
	ICON = 'Spell_Shadow_CurseOfSargeras',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 24,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CURSEOFEXHAUSTION] = {
	ICON = 'Spell_Shadow_GrimWard',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 12,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CURSEOFELEMENTS] = {
	ICON = 'Spell_Shadow_ChillTouch',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 300,
	MONITOR = false,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CURSEOFSHADOW] = {
	ICON = 'Spell_Shadow_CurseOfAchimonde',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 300,
	MONITOR = false,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CURSEOFTONGUES] = {
	ICON = 'Spell_Shadow_CurseOfTounges',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 30,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CURSEOFWEAKNESS] = {
	ICON = 'Spell_Shadow_CurseOfMannoroth',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 120,
	MONITOR = false,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CURSEOFRECKLESSNESS] = {
	ICON = 'Spell_Shadow_UnholyStrength',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 120,
	MONITOR = false,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_CURSEOFDOOM] = {
	ICON = 'Spell_Shadow_AuraOfDarkness',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 60,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_SIPHONLIFE] = {
	ICON = 'Spell_Shadow_Requiem',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 30,
	MONITOR = false,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_IMPROVEDSHADOWBOLT] = {
	ICON = 'Spell_Shadow_ShadowBolt',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 12,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_SPELLLOCK] = {
	ICON = 'Spell_Shadow_MindRot',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 3,
	MONITOR = true,
	WARN = 0,
}
-- Warrior - Debuffs
CCWATCH.CCS[CCWATCH_DISARM] = {
	ICON = 'Ability_Warrior_Disarm',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 10,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_MORTALSTRIKE] = {
	ICON = 'Ability_Warrior_SavageBlow',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 10,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_REND] = {
	ICON = 'Ability_Gouge',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 21,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_HAMSTRING] = {
	ICON = 'Ability_ShockWave',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 15,
	MONITOR = true,
	WARN = 0,
}
-- Shaman - Debuffs

CCWATCH.CCS[CCWATCH_FROSTSHOCK] = {
	ICON = 'Spell_Frost_FrostShock',
	SCHOOL = CCWATCH_SCHOOL.FROST,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 8,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.CCS[CCWATCH_FLAMESHOCK] = {
	ICON = 'Spell_Fire_FlameShock',
	SCHOOL = CCWATCH_SCHOOL.FIRE,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 12,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_FROSTBRANDWEAPON] = {
	ICON = 'Spell_Frost_FrostBrand',
	SCHOOL = CCWATCH_SCHOOL.FROST,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 8,
	MONITOR = true,
	WARN = 0,
}
CCWATCH.CCS[CCWATCH_STORMSTRIKE] = {
	ICON = 'Spell_Holy_SealOfMight',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_DEBUFF,
	DURATION = 12,
	MONITOR = true,
	WARN = 0,
}

-- Specific - Debuffs

end