function CCWatch_ConfigCC()

-- required attributes: GROUP, DURATION, DIMINISHES
--  ETYPE = Effect Type : ETYPE_CC Pure CC(Stun/Root), ETYPE_DEBUFF Debuff(Snare/DoT,...), ETYPE_BUFF Buff
--  GROUP = Bar this CC is placed on
--  DURATION = Duration of CC
--  DIMINISHES = 0 never diminishes, 1 = always diminishes, 2 = diminishes on players only
-- optional attributes PVPCC, COMBO
--  PVPCC = if PVPCC exists this value will be used as the base max for a Player target
--  COMBO = if COMBO exists then Combo Points will be added to CC duration
--
-- TARGET, PLAYER, TIMER_START, TIMER_END, DIMINISH are required for all and should be initialized empty
-- MONITOR is required for all and should be initialized to true
-- WARN is required for all and should be initialized to 0

-- Rogue - Stun/Root CCs
CCWATCH.EFFECTS[CCWATCH_GOUGE] = {
	ICON = 'Ability_Gouge',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 4,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_BLIND] = {
	ICON = 'Spell_Shadow_MindSteal',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 10,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_SAP] = {
	ICON = 'Ability_Sap',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 45,
	PVP_DURATION = 15,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_KS] = {
	ICON = 'Ability_Rogue_KidneyShot',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 1,
	COMBO = true,
	A = 1, -- f(x) = A * x + DURATION => 1 point = 2 sec, 5 point = 6 sec
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_CS] = {
	ICON = 'Ability_CheapShot',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 4,
	MONITOR = true,
	WARN = 0,
}

-- Priest - Stun/Root CCs
CCWATCH.EFFECTS[CCWATCH_SHACKLE] = {
	ICON = 'Spell_Nature_Slow',
	SCHOOL = CCWATCH_SCHOOL.HOLY,
	ETYPE = ETYPE_CC,
	DURATION = 30,	-- 40 50
	MONITOR = true,
	WARN = 0,
	DIMINISH = 0
}

CCWATCH.EFFECTS[CCWATCH_PSYCHICSCREAM] = {
	ICON = 'Spell_Shadow_PsychicScream',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_CC,
	DURATION = 8,
	MONITOR = true,
	WARN = 0,
	DIMINISH = 0
}

CCWATCH.EFFECTS[CCWATCH_BLACKOUT] = {
	ICON = 'Spell_Shadow_GatherShadows',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_CC,
	DURATION = 2,
	MONITOR = true,
	WARN = 0,
	DIMINISH = 0
}

-- Mage - Stun/Root CCs
CCWATCH.EFFECTS[CCWATCH_POLYMORPH] = {
	ICON = 'Spell_Nature_Polymorph', -- Spell_Magic_PolymorphPig, TODO Ability_Hunter_Pet_Turtle
	SCHOOL = CCWATCH_SCHOOL.ARCANE,
	ETYPE = ETYPE_CC,
	DURATION = 20,
	PVP_DURATION = 15,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_FROSTNOVA] = {
	ICON = 'Spell_Frost_FreezingBreath',
	SCHOOL = CCWATCH_SCHOOL.FROST,
	ETYPE = ETYPE_CC,
	DURATION = 8,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_FROSTBITE] = {
	ICON = 'Spell_Frost_FrostArmor',
	SCHOOL = CCWATCH_SCHOOL.FROST,
	ETYPE = ETYPE_CC,
	DURATION = 5,
	MONITOR = true,
	WARN = 0,
}

-- Druid - Stun/Root CCs
CCWATCH.EFFECTS[CCWATCH_ROOTS] = {
	ICON = 'Spell_Nature_StrangleVines',
	SCHOOL = CCWATCH_SCHOOL.NATURE,
	ETYPE = ETYPE_CC,
	DURATION = 12, -- 15 18 21 24 27
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_HIBERNATE] = {
	ICON = 'Spell_Nature_Sleep',
	SCHOOL = CCWATCH_SCHOOL.NATURE,
	ETYPE = ETYPE_CC,
	DURATION = 20, -- 30 40
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_FERALCHARGE] = {
	ICON = 'Ability_Hunter_Pet_Bear',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 4,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_IMPSTARFIRE] = {
	ICON = 'Spell_Arcane_StarFire',
	SCHOOL = CCWATCH_SCHOOL.ARCANE,
	ETYPE = ETYPE_CC,
	DURATION = 3,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_POUNCE] = {
	ICON = 'Ability_Druid_SupriseAttack',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 2,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_BASH] = {
	ICON = 'Ability_Druid_Bash',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 2, -- 2, 3, 4
	MONITOR = true,
	WARN = 0,
}

-- Hunter - Stun/Root CCs
CCWATCH.EFFECTS[CCWATCH_FREEZINGTRAP] = {
	ICON = 'Spell_Frost_ChainsOfIce',
	SCHOOL = CCWATCH_SCHOOL.FROST,
	ETYPE = ETYPE_CC,
	DURATION = 10, -- 15 20
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_IMPCS] = {
	ICON = 'Spell_Frost_IceShock',
	SCHOOL = CCWATCH_SCHOOL.ARCANE,
	ETYPE = ETYPE_CC,
	DURATION = 4,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_SCAREBEAST] = {
	ICON = 'Ability_Druid_Cower',
	SCHOOL = CCWATCH_SCHOOL.NATURE,
	ETYPE = ETYPE_CC,
	DURATION = 10, -- 15 20
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_SCATTERSHOT] = {
	ICON = 'Ability_GolemStormBolt',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 4, -- 15 20
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_INTIMIDATION] = {
	ICON = 'Ability_Devour',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 3, -- 15 20
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_COUNTERATTACK] = {
	ICON = 'Ability_Warrior_Challange',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 5,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_IMPROVEDWINGCLIP] = {
	ICON = 'Ability_Rogue_Trip',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 5,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_WYVERNSTING] = {
	ICON = 'INV_Spear_02',
	SCHOOL = CCWATCH_SCHOOL.NATURE,
	ETYPE = ETYPE_CC,
	DURATION = 12,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_ENTRAPMENT] = {
	ICON = 'Spell_Nature_StrangleVines',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 5,
	MONITOR = true,
	WARN = 0,
}

-- Paladin - Stun/Root CCs
CCWATCH.EFFECTS[CCWATCH_HOJ] = {
	ICON = 'Spell_Holy_SealOfMight',
	SCHOOL = CCWATCH_SCHOOL.HOLY,
	ETYPE = ETYPE_CC,
	DURATION = 3, -- 4 5 6
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_REPENTANCE] = {
	ICON = 'Spell_Holy_PrayerOfHealing',
	SCHOOL = CCWATCH_SCHOOL.HOLY,
	ETYPE = ETYPE_CC,
	DURATION = 6,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_TURNUNDEAD] = {
	ICON = 'Spell_Holy_TurnUndead',
	SCHOOL = CCWATCH_SCHOOL.HOLY,
	ETYPE = ETYPE_CC,
	DURATION = 10, -- 15 20
	MONITOR = true,
	WARN = 0,
}

-- Warlock - Stun/Root CCs
CCWATCH.EFFECTS[CCWATCH_SEDUCE] = {
	ICON = 'Spell_Shadow_MindSteal',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_CC,
	DURATION = 15,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_FEAR] = {
	ICON = 'Spell_Shadow_Possession',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_CC,
	DURATION = 10, -- 15 20
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_HOWLOFTERROR] = {
	ICON = 'Spell_Shadow_DeathScream',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_CC,
	DURATION = 10, -- 15
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_DEATHCOIL] = {
	ICON = 'Spell_Shadow_DeathCoil',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_CC,
	DURATION = 3,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_BANISH] = {
	ICON = 'Spell_Shadow_Cripple',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_CC,
	DURATION = 20, -- 30
	MONITOR = true,
	WARN = 0,
}

-- Warrior - Stun/Root CCs
CCWATCH.EFFECTS[CCWATCH_INTERCEPT] = {
	ICON = 'Ability_Rogue_Sprint',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 3,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_MACESPE] = {
	ICON = 'INV_Mace_01',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 3,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_HAMSTRING] = {
	ICON = 'Ability_ShockWave',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 15,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_IMPHAMSTRING] = {
	ICON = 'Ability_ShockWave',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 3,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_INTIMIDATINGSHOUT] = {
	ICON = 'Ability_GolemThunderClap',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 8,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_IMPREVENGE] = {
	ICON = 'Ability_Warrior_Revenge',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 3,
	MONITOR = true,
	WARN = 0,
}

CCWATCH.EFFECTS[CCWATCH_CONCUSSIONBLOW] = {
	ICON = 'Ability_ThunderBolt',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 5,
	MONITOR = true,
	WARN = 0,
}

-- Specific - Stun/Root CCs

-- Tauren
CCWATCH.EFFECTS[CCWATCH_WARSTOMP] = {
	ICON = 'Ability_WarStomp',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 2,
	MONITOR = true,
	WARN = 0,
}

-- Green Whelp Armour
CCWATCH.EFFECTS[CCWATCH_SLEEP] = {
	ICON = 'Spell_Holy_MindVision',
	SCHOOL = CCWATCH_SCHOOL.SHADOW,
	ETYPE = ETYPE_CC,
	DURATION = 30,
	MONITOR = true,
	WARN = 0,
}

-- Net O Matic
CCWATCH.EFFECTS[CCWATCH_NETOMATIC] = {
	ICON = 'INV_Misc_Net_01',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 10,
	MONITOR = true,
	WARN = 0,
}

-- Reckless Helmet
CCWATCH.EFFECTS[CCWATCH_ROCKETHELM] = {
	ICON = 'INV_Helmet_49',
	SCHOOL = CCWATCH_SCHOOL.PHYSICAL,
	ETYPE = ETYPE_CC,
	DURATION = 30,
	MONITOR = true,
	WARN = 0,
}

end